// This file contains the word lists for the Wordle game
// VALID_WORDS are words that can be the solution
// VALID_GUESSES are additional words that players can enter as guesses

const VALID_WORDS = [
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "ankle", "apart", "apple", "apply",
    "arena", "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award",
    "aware", "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin", "begun",
    "being", "below", "bench", "billy", "birth", "black", "blame", "blank", "blast", "bleed",
    "blend", "bless", "blind", "block", "blood", "board", "boost", "booth", "bound", "brain",
    "brand", "bread", "break", "breed", "brief", "bring", "broad", "broke", "brown", "build",
    "built", "buyer", "cable", "calif", "carry", "catch", "cause", "chain", "chair", "chart",
    "chase", "cheap", "check", "chest", "chief", "child", "china", "chose", "civil", "claim",
    "class", "clean", "clear", "click", "clock", "close", "coach", "coast", "could", "count",
    "court", "cover", "craft", "crash", "cream", "crime", "cross", "crowd", "crown", "curve",
    "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay", "depth", "doing",
    "doubt", "dozen", "draft", "drama", "drawn", "dream", "dress", "drill", "drink", "drive",
    "drove", "dying", "eager", "early", "earth", "eight", "elite", "empty", "enemy", "enjoy",
    "enter", "entry", "equal", "error", "event", "every", "exact", "exist", "extra", "faith",
    "false", "fault", "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed",
    "flash", "fleet", "floor", "fluid", "focus", "force", "forth", "forty", "forum", "found",
    "frame", "frank", "fraud", "fresh", "front", "fruit", "fully", "funny", "giant", "given",
    "glass", "globe", "going", "grace", "grade", "grand", "grant", "grass", "great", "green",
    "gross", "group", "grown", "guard", "guess", "guest", "guide", "happy", "harry", "heart",
    "heavy", "hence", "henry", "horse", "hotel", "house", "human", "ideal", "image", "index",
    "inner", "input", "issue", "japan", "jimmy", "joint", "jones", "judge", "known", "label",
    "large", "laser", "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal",
    "level", "lewis", "light", "limit", "links", "lives", "local", "logic", "loose", "lower",
    "lucky", "lunch", "lying", "magic", "major", "maker", "march", "maria", "match", "maybe",
    "mayor", "meant", "media", "metal", "might", "minor", "minus", "mixed", "model", "money",
    "month", "moral", "motor", "mount", "mouse", "mouth", "movie", "music", "needs", "never",
    "newly", "night", "noise", "north", "noted", "novel", "nurse", "occur", "ocean", "offer",
    "often", "order", "other", "ought", "paint", "panel", "paper", "party", "peace", "peter",
    "phase", "phone", "photo", "piece", "pilot", "pitch", "place", "plain", "plane", "plant",
    "plate", "point", "pound", "power", "press", "price", "pride", "prime", "print", "prior",
    "prize", "proof", "proud", "prove", "queen", "quick", "quiet", "quite", "radio", "raise",
    "range", "rapid", "ratio", "reach", "ready", "refer", "right", "rival", "river", "robin",
    "roger", "roman", "rough", "round", "route", "royal", "rural", "scale", "scene", "scope",
    "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp", "sheet", "shelf",
    "shell", "shift", "shirt", "shock", "shoot", "short", "shown", "sight", "since", "sixth",
    "sixty", "sized", "skill", "sleep", "slide", "small", "smart", "smile", "smith", "smoke",
    "solid", "solve", "sorry", "sound", "south", "space", "spare", "speak", "speed", "spend",
    "spent", "split", "spoke", "sport", "staff", "stage", "stake", "stand", "start", "state",
    "steam", "steel", "stick", "still", "stock", "stone", "stood", "store", "storm", "story",
    "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "super", "sweet", "table",
    "taken", "taste", "taxes", "teach", "teeth", "terry", "texas", "thank", "theft", "their",
    "theme", "there", "these", "thick", "thing", "think", "third", "those", "three", "threw",
    "throw", "tight", "times", "tired", "title", "today", "topic", "total", "touch", "tough",
    "tower", "track", "trade", "train", "treat", "trend", "trial", "tried", "tries", "truck",
    "truly", "trust", "truth", "twice", "under", "undue", "union", "unity", "until", "upper",
    "upset", "urban", "usage", "usual", "valid", "value", "video", "virus", "visit", "vital",
    "voice", "waste", "watch", "water", "wheel", "where", "which", "while", "white", "whole",
    "whose", "woman", "women", "world", "worry", "worse", "worst", "worth", "would", "wound",
    "write", "wrong", "wrote", "yield", "young", "youth"
];

// Additional valid guesses (these won't be chosen as solutions but are valid guesses)
const VALID_GUESSES = [
    "aahed", "aalii", "aargh", "abaca", "abaci", "aback", "abaft", "abaka", "abamp", "abase",
    "abash", "abate", "abbas", "abbes", "abbey", "abbot", "abeam", "abele", "abets", "abhor",
    "abide", "abies", "abler", "ables", "abmho", "abode", "abohm", "aboil", "aboon", "abort",
    "abris", "abune", "abuse", "abuts", "abuzz", "abyes", "abysm", "abyss", "acari", "acerb",
    "aceta", "ached", "aches", "achoo", "acids", "acidy", "acing", "acini", "ackee", "acmes",
    "acned", "acnes", "acock", "acold", "acorn", "acred", "acres", "acrid", "acros", "acted",
    "actin", "acton", "actor", "acute", "acyls", "adage", "adapt", "addax", "added", "adder",
    "addle", "adeem", "adept", "adieu", "adios", "adits", "adman", "admen", "admit", "admix",
    "adobe", "adobo", "adopt", "adore", "adorn", "adown", "adoze", "adult", "adunc", "adust",
    "adyta", "adzed", "adzes", "aecia", "aedes", "aegis", "aeons", "aerie", "afars", "affix",
    "afire", "afoot", "afore", "afoul", "afrit", "after", "again", "agama", "agape", "agars",
    "agate", "agave", "agaze", "agene", "agent", "agers", "agger", "aggie", "aggro", "aghas",
    "agile", "aging", "agios", "agism", "agist", "agita", "aglee", "aglet", "agley", "aglow",
    "agmas", "agone", "agons", "agony", "agora", "agree", "agria", "agues", "ahead", "ahing",
    "ahold", "ahull", "aided", "aider", "aides", "ailed", "aimed", "aimer", "aioli", "aired",
    "airer", "airns", "airth", "airts", "aisle", "aitch", "ajiva", "ajuga", "akees", "akela",
    "akene", "alack", "alamo", "aland", "alane", "alang", "alans", "alant", "alarm", "alary",
    "alate", "albas", "album", "alcid", "alder", "aldol", "alecs", "alefs", "aleph", "alert",
    "alfas", "algae", "algal", "algas", "algid", "algin", "algor", "algum", "alias", "alibi",
    "alien", "alifs", "align", "alike", "aline", "alist", "alive", "aliya", "alkie", "alkyd",
    "alkyl", "allay", "allee", "allel", "alley", "allod", "allot", "allow", "alloy", "allyl",
    "almah", "almas", "almeh", "almes", "almud", "almug", "aloes", "aloft", "aloha", "aloin",
    "alone", "along", "aloof", "aloud", "alpha", "altar", "alter", "altho", "altos", "alula",
    "alums", "alway", "amahs", "amain", "amass", "amaze", "amber", "ambit", "amble", "ambos",
    "ambry", "ameba", "ameer", "amend", "amens", "ament", "amias", "amice", "amici", "amide",
    "amido", "amids", "amies", "amiga", "amigo", "amine", "amino", "amins", "amirs", "amiss",
    "amity", "ammos", "amnia", "amnic", "amnio", "amoks", "amole", "among", "amort", "amour",
    "amped", "ample", "amply", "ampul", "amuck", "amuse", "amyls", "anana", "anata", "anded",
    "anele", "anent", "angas", "angel", "anger", "angle", "anglo", "angry", "angst", "anile",
    "anils", "anima", "anime", "animi", "anion", "anise", "ankhs", "ankle", "ankus", "anlas",
    "annal", "annas", "annex", "annoy", "annul", "anoas", "anode", "anole", "anomy", "ansae",
    "antae", "antas", "anted", "antes", "antic", "antis", "antra", "antre", "antsy", "anvil",
    "anyon", "aorta", "apace", "apart", "apeak", "apeek", "apers", "apery", "aphid", "aphis",
    "apian", "aping", "apish", "apnea", "apods", "aport", "appal", "appel", "apple", "apply",
    "apres", "apron", "apses", "apsis", "apter", "aptly", "aquae", "aquas", "araks", "arame",
    "arbor", "arced", "arcus", "ardeb", "ardor", "areae", "areal", "areas", "areca", "areic",
    "arena", "arene", "arepa", "arete", "argal", "argil", "argle", "argol", "argon", "argot",
    "argue", "argus", "arhat", "arias", "ariel", "arils", "arise", "arles", "armed", "armer",
    "armet", "armor", "aroid", "aroma", "arose", "arpen", "arras", "array", "arris", "arrow",
    "arses", "arsis", "arson", "artal", "artel", "artsy", "aruhe", "arums", "arval", "arvos",
    "aryls", "asana", "ascot", "ascus", "asdic", "ashed", "ashen", "ashes", "aside", "asked",
    "asker", "askew", "askoi", "askos", "aspen", "asper", "aspic", "aspis", "assai", "assay",
    "asses", "asset", "aster", "astir", "asyla", "ataps", "ataxy", "atilt", "atlas", "atman",
    "atmas", "atoll", "atoms", "atomy", "atone", "atony", "atopy", "atria", "atrip", "attap",
    "attar", "attic", "audio", "audit", "auger", "aught", "augur", "aulic", "aunts", "aunty",
    "aurae", "aural", "aurar", "auras", "aurei", "aures", "auric", "auris", "aurum", "autos",
    "auxin", "avail", "avast", "avens", "avers", "avert", "avgas", "avian", "avion", "aviso",
    "avoid", "avows", "await", "awake", "award", "aware", "awash", "awful", "awing", "awned",
    "awoke", "axels", "axial", "axile", "axils", "axing", "axiom", "axion", "axite", "axled",
    "axles", "axman", "axmen", "axone", "axons", "ayahs", "ayins", "azans", "azide", "azido",
    "azine", "azlon", "azoic", "azole", "azons", "azote", "azoth", "azuki", "azure"
];

// Combine both lists for valid guesses
VALID_GUESSES.push(...VALID_WORDS);
